# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    AppBundle\Entity\Contentuser:
      algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory:
      memory: ~
    our_db_provider:
      entity:
        class: AppBundle:Contentuser
        property: username


  firewalls:

# disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
#login, also path to login form and more!
    main:
      anonymous: ~
      provider: our_db_provider
      form_login:
        login_path: adminlogin
        check_path: adminlogin
      remember_me:
        secret: '%secret%' #secret key from parameter.yml
        lifetime: 604800 #1 weak in seconds
        path: /
      logout:
        path: /giantcontent/logout
        target: /
      # For unit testing
      http_basic: ~

   #   access controll path what are checked of login priv.
  access_control:
    - { path: ^/giantcontent, roles: ROLE_ADMIN }
   #full https for the whole site, needs https server
   # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

# activate different ways to authenticate

# http_basic: ~
# http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate



