<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * HomeContentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeContentRepo extends EntityRepository
{





}
