<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * HomeContentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeContentRepo extends EntityRepository
{
    public function contentJoin()
    {
        $query=$this->getEntityManager()
            ->createQuery(
                '
                SELECT h,c
                FROM AppBundle:Homecontent h
                JOIN h.author c
                ');
        return $query->getResult();

    }



}
