<?php
namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * VideoRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepo extends EntityRepository
{
    public function VideoLeftJoin($videoID)
    {
        $query=$this->getEntityManager()
            ->createQuery(
                'SELECT v,a FROM AppBundle:Video v
                JOIN v.album a
                where v.album =:id'
            )->setParameter('id',$videoID);
        return $query->getResult();
    }
    /*
    SELECT alben.alben_id,alben.name,alben.release
    FROM alben
    INNER JOIN video
    ON alben.alben_id=video.album*/
}